---
abstract: 'Simple and Efficient Reading/Writing/Modifying of Complete Files'
author:
  - 'Uri Guttman <uri@stemsystems.com>'
build_requires:
  B: '0'
  Carp: '0'
  Exporter: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::Temp: '0'
  IO::Handle: '0'
  POSIX: '0'
  Scalar::Util: '0'
  Socket: '0'
  Symbol: '0'
  Test::More: '0'
  overload: '0'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-Slurp
no_index:
  directory:
    - t
    - inc
requires:
  B: '0'
  Carp: '0'
  Errno: '0'
  Exporter: '0'
  Fcntl: '0'
  POSIX: '0'
  strict: '0'
  warnings: '0'
version: 9999.20_02
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
